####Options####

#Measured in metres, where one metre equates to the length of one Minecraft block.
metrics:
  maximumChatDistance: 20

####Text####

lang:
  announceNameToSender: You announce your name.
  announceNameToListeners: My name is _1. 
  announceNameFail: Nobody appears to have heard that.
  
  setNameMessage: You decide to call yourself _1.

####Saved Data####

save:
  names:
    