####Options####

#Measured in metres, where one metre equates to the length of one Minecraft block.
metrics:
  maximumChatDistance: 20

####Text####

lang:
  announceNameToSender: §O§2You announce your name.
  announceNameToListeners: My name is _1. 
  announceNameFail: §O§2Nobody appears to have heard that.

####Generated####