name: Allure
main: com.lyesoussaiden.allure.Allure
version: 0.1
author: Lyes Oussaiden
website: https://github.com/Mr-Rockers/allure
commands:
  tellName:
    description: Announces your name to nearby players.
    aliases: [tN, tellname]
    usage: Simply type /tN to announce your name to those nearby. (They won't forget!)