name: Allure
main: com.lyesoussaiden.allure.Allure
version: 0.1
author: Lyes Oussaiden
website: https://github.com/Mr-Rockers/allure
commands:
  tellname:
    description: Announces your name to all players that can hear you.
    aliases: [tN]
    usage: Simply type /tellname or /tN to announce your name to those nearby. (They won't forget!)